files: ^starter/
repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        types:
          - python
        language_version: python3
        args:
          - --line-length
          - &line_length "88"
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types:
          - python
        args:
          - --max-line-length
          - *line_length
          - --ignore=D100,D202,D104,D205,D201,D212,W503,W605,E712,E731,E501
  # D100 requires all Python files (modules) to have a "public" docstring even if all functions within have a docstring.
  # D104 requires __init__ files to have a docstring
  # W503 requires no binary operators just after a line feed, but that is how black auto-formats our long Spark commands
  # W605 doesn't allow `\d` escape sequences but they are useful in regex (where they are not actually escape sequences)
  # E712 requires alternative syntax for conditionals that isn't Spark compatible
  # E731 does not allow for lambda expressions
  # E505 limits line length to 90 chars.
  
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: system
        types:
          - python
        args:
          - --profile=black
          - --line-length
          - *line_length